// export const GET_SHARE_COURSE_TEACHER_LIST = 'GET_SHARE_COURSE_TEACHER_LIST'
export const CHANGE_MENUS = 'CHANGE_MENUS'
export const CHANGE_TREE_DATA = 'CHANGE_TREE_DATA'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'